### ISSUE TITLE
Deploy qubes-updates-cache by default (So updates packages are downloaded once and picked by every TemplateVMs)

### ISSUE THREAD

**Issue by tlaurion** [SkypLabs/my-qubes-os-formula#5]
Clone, build and deploy [qubes-updates-cache]( https://github.com/rustybird/qubes-updates-cache) so packages are downloaded only once from the network, while being installed on all cloned templates.

**Comment by SkypLabs** [comment]
Great idea! I will have a look at it when I will find a moment. Thanks.

**Comment by tlaurion** [comment]
@unman?

**Comment by tlaurion** [comment]
Exists under qusal and shaker.
